version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch-api
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  kibana:
      image: docker.elastic.co/kibana/kibana:6.6.0
      hostname: kibana-api
      links:
          - elasticsearch
      ports:
          - "5601:5601"
      volumes:
          - "./elasticsearch/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml"
      depends_on:
          - elasticsearch
      networks:
        - esnet
  restfull-app:
      container_name: "cluster-api"
      restart: always
      build:
        context: ./cluster
        dockerfile: Dockerfile
      volumes:
        - ./cluster/:/cluster/
        - ./export01-newspapers1841-1878/export01-newspapers1841-1878:/data
      ports:
        - 5001:5001
      networks:
        - esnet
volumes:
  esdata2:
    driver: local
networks:
  esnet: